### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by flex-luthor** [Devsoc-BPGC/chocolate-mint#3]
Add Storybook in the React App and configure it to run at port 4500.
Storybook docs : - https://storybook.js.org/docs/basics/introduction/

**Comment by snigdha2210** [comment]
I forked the repo, made the changes (added storybook and configured it to run at port 4500) in a new branch, but as i check the status, it says "nothing to commit, working tree clean"
I don't understand, someone pls look into it.

**Comment by flex-luthor** [comment]
You're running "git push origin your-branch" and not "git push origin master" right?

**Comment by flex-luthor** [comment]
This issue is resolved.
